name: bloc_arch
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:

  easy_localization: 3.0.7+1
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: 5.1.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  retrofit: ^4.4.2
  internet_connection_checker: ^3.0.1
  auto_route: ^10.0.1
  fluttertoast: ^8.2.12
  flutter_dotenv: ^5.2.1
  loading_animation_widget: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  injectable: ^2.5.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.7
  multi_select_flutter: ^4.1.3
  dropdown_search:
    path: dropdown_search-5.0.6
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.0.0

  cupertino_icons: ^1.0.8
  cron: ^0.6.2
  flutter_secure_storage: ^4.2.1
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  pretty_dio_logger: ^1.4.0
  injectable_generator: ^2.5.0
  drift_dev: ^2.20.0
  #  mockito: ^5.4.6
  #  http_mock_adapter: ^0.6.1
  #  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/translations/
  uses-material-design: true

