// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0pqnP7zBdeYrbN4UR5EcpVIvgvqIHvY',
    appId: '1:762255622193:web:24f94ff741147a6c769510',
    messagingSenderId: '762255622193',
    projectId: 'tech-test-task-managment',
    authDomain: 'tech-test-task-managment.firebaseapp.com',
    storageBucket: 'tech-test-task-managment.firebasestorage.app',
    measurementId: 'G-LRYZT84MD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEN4nthsVXVfDQajH_WTYm0cVKAzMLbx4',
    appId: '1:762255622193:android:f45ac3d20f1d4e01769510',
    messagingSenderId: '762255622193',
    projectId: 'tech-test-task-managment',
    storageBucket: 'tech-test-task-managment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAoe2nhB5nwo3UEpBK2KHUfV7Fj82laUI',
    appId: '1:762255622193:ios:94bc0a1596a65e95769510',
    messagingSenderId: '762255622193',
    projectId: 'tech-test-task-managment',
    storageBucket: 'tech-test-task-managment.firebasestorage.app',
    iosBundleId: 'com.example.blocArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAoe2nhB5nwo3UEpBK2KHUfV7Fj82laUI',
    appId: '1:762255622193:ios:94bc0a1596a65e95769510',
    messagingSenderId: '762255622193',
    projectId: 'tech-test-task-managment',
    storageBucket: 'tech-test-task-managment.firebasestorage.app',
    iosBundleId: 'com.example.blocArch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt0pqnP7zBdeYrbN4UR5EcpVIvgvqIHvY',
    appId: '1:762255622193:web:b205311c5c77b55f769510',
    messagingSenderId: '762255622193',
    projectId: 'tech-test-task-managment',
    authDomain: 'tech-test-task-managment.firebaseapp.com',
    storageBucket: 'tech-test-task-managment.firebasestorage.app',
    measurementId: 'G-CWX281SFP5',
  );
}
